author: &author
  name: &author_name ArÄ¥imedeÏ‚ MontegasppÎ± CacilhÎ±Ï‚
  email: batalema@cacilhas.info
  url: //montegasppa.cacilhas.info/author.html
  contacts:
    devto:
      name: DEV Profile ğŸ‘©â€ğŸ’»ğŸ‘¨â€ğŸ’»
      title: DEV Profile ğŸ‘©â€ğŸ’»ğŸ‘¨â€ğŸ’»
      url: https://dev.to/cacilhas
    twitter:
      name: Twitter
      title: ArÄ¥imedeÏ‚ â„³ontegasppÎ±
      url: https://twitter.com/Montegasppa
      image:
        source: //cacilhas.info/img/twitter.png
        style:
          width: 24px
          height: 24px
    patreon:
      name: Patreon
      title: â„³ontegasppÎ±
      url: https://www.patreon.com/cacilhas
      image:
        source: //cacilhas.info/img/patreon.png
        style:
          width: 24px
          height: 24px
    bandcamp:
      name: Bandcamp
      title: Le Obscur EssenteÏ‚
      url: https://montegasppa.bandcamp.com/releases
      image:
        source: //cacilhas.info/img/le-obscur-essentes.jpg
        style:
          width: 24px
          height: 24px
    github:
      name: Github
      url: https://github.com/cacilhas/
      image:
        source: //cacilhas.info/img/github.png
        style:
          width: 24px
          height: 20px
    facebook:
      name: Facebook
      title: Archimedes Montegasppa
      url: https://www.facebook.com/archimedes.montegasppa.3
      image:
        source: //cacilhas.info/img/facebook.png
        style:
          width: 24px
          height: 24px
    linkedin:
      name: LinkedIn
      title: Rodrigo Cacilhas
      url: https://br.linkedin.com/in/rodrigocacilhas
      image:
        source: //cacilhas.info/img/linkedin.png
        style:
          width: 24px
          height: 24px

description: The shadows behind the code.
favicon: /img/favicon.ico
image: /img/background.jpg
lang: en
site: &site //kodumaro.cacilhas.info
title: &title Kodumaro

license:
  name: CC-BY 4.0
  url: http://creativecommons.org/licenses/by/4.0/deed
  image: https://i.creativecommons.org/l/by/4.0/80x15.png

blog:
  author: *author
  url: *site
  title: *title

devto:
  title: DEV Profile ğŸ‘©â€ğŸ’»ğŸ‘¨â€ğŸ’»
  url: https://dev.to/cacilhas
  badge: https://d2fltix0v2e0sb.cloudfront.net/dev-badge.svg

cacilhas:
  title: â„­acilhÎ±Ï‚.INFO
  url: //cacilhas.info

hondaj:
  title: Ä¤Ã¸Å…ÄÎ”jÌ†â‚€
  url: //hondaj.cacilhas.info/

mastodon:
  title: Mastodon
  url: https://social.sndevs.com/@kodumaro
  account: "@kodumaro@social.sndevs.com"
  badge: //cacilhas.info/img/mastodon.png

misc:
  title: Miscelaneous
  url: //cacilhas.info/misc

montegasppa:
  title: â„³ontegasppÎ± and Giulia C.â€™s Thoughts
  url: //montegasppa.cacilhas.info/
  author: *author_name

mosaicolivre:
  title: Mosaico Livre
  url: https://claudiotorcato.wordpress.com/
  author: ClÃ¡udio Torcato

patreon:
  title: Kodumaro at Patreon
  url: https://www.patreon.com/kodumaro
  author: *author_name

todasfridas:
  title: Todas Fridas
  url: https://www.todasfridas.com.br/

vortaro:
  title: Konsulta Vortaro
  url: //vortaro.cacilhas.info/

waltercruz:
  title: Walter Cruz
  url: https://waltercruz.com/
  author: Walter Cruz

googlead:
  client: ca-pub-5741846017654057
  id: UA-99357497-1
  slot: 7936078120
